branches:
  only:
  - master
language: r
sudo: false
git:
  depth: false
cache: 
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/Supports_formations/m1_socle/_book
    - $TRAVIS_BUILD_DIR/Supports_formations/m1_socle/_bookdown_files
    - $TRAVIS_BUILD_DIR/Supports_formations/m2_preparation_donnees/_book
    - $TRAVIS_BUILD_DIR/Supports_formations/m2_preparation_donnees/_bookdown_files
    - $TRAVIS_BUILD_DIR/Supports_formations/m3_stats_desc/_book
    - $TRAVIS_BUILD_DIR/Supports_formations/m3_stats_desc/_bookdown_files
    - $TRAVIS_BUILD_DIR/Supports_formations/m4_analyse_donnees/_book
    - $TRAVIS_BUILD_DIR/Supports_formations/m4_analyse_donnees/_bookdown_files
    - $TRAVIS_BUILD_DIR/Supports_formations/m5_valorisation_des_donnees/_book
    - $TRAVIS_BUILD_DIR/Supports_formations/m5_valorisation_des_donnees/_bookdown_files
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libxml2
      - cargo

before_script:
  - chmod +x ./_build.sh
#  - chmod +x ./_build_only_m3.sh
  - chmod +x ./_deploy.sh
      
script:
  - ./_build.sh

deploy:
  provider: script
  script: ./_deploy.sh
  skip_cleanup: true
